// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersionAttribute("0.1.0.64")]
[assembly: AssemblyFileVersionAttribute("0.1.0.64")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-dev.0+d372c5d")]
